### ISSUE TITLE
SHA256 mismatch for flite

### ISSUE THREAD

**Issue by hoffbaked** [FreeSWITCH/homebrew-freeswitch#3]
I'm trying to follow the instructions to install FreeSwitch on OS X, El Capitan, and I'm stopped by hash mismatch on this file:

David-Hoffs-MacBook-Air:freeswitch dhoff$ brew install FreeSWITCH/homebrew-freeswitch/flite
==> Installing flite from freeswitch/freeswitch
==> Downloading http://files.freeswitch.org/downloads/libs/flite-2.0.0.tar.gz
###### ################################################################## 100.0%

Error: SHA256 mismatch
Expected: fe3b4b653739d714d47042333d3634ea0ab93362addd4e968840f837045dd345
Actual: 3a66c544373c5905fafb1314bc0e4988ef9e0993b79d1448f68a756ca8b96e21
Archive: /Library/Caches/Homebrew/flite-2.0.0.tar.gz
To retry an incomplete download, remove the file above.

The file decompresses into a tar file, and it looks like the file was recently changed, so I'm assuming the hash needs to be updated or something.

**Comment by mjerris** [comment]
pushed a change for this, please give it a try and confirm its better now.

**Comment by anupamnath** [comment]
Same problem. @mjerris plz kindly update it once again!!!

I am experiencing similar issue but with different key.

After repeated removal and downloads, still stuck at the following -

==> Installing flite from freeswitch/freeswitch
==> Downloading http://files.freeswitch.org/downloads/libs/flite-2.0.0.tar.gz
Already downloaded: /Users/n00b/Library/Caches/Homebrew/flite-2.0.0.tar.gz
Error: SHA256 mismatch
Expected: 3a66c544373c5905fafb1314bc0e4988ef9e0993b79d1448f68a756ca8b96e21
Actual: 4beb74f8f674cf8eec0f1d68e16e1660b32003de10328797aafa61c7d59cc72a
Archive: /Users/n00b/Library/Caches/Homebrew/flite-2.0.0.tar.gz
To retry an incomplete download, remove the file above.

Please kindly update the sha256 for flite tarball.

Thanks.  Any fixes appreciated.

**Comment by mjerris** [comment]
dup of issue 4, pr merged
